<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Engineer;
use App\Models\Specialty;
use App\Models\University;
use Illuminate\Database\Seeder;

class EngineerSeeder extends Seeder
{
    public function run(): void
    {
        $engineers = [
            [
                'rni' => '100001',
                'ci' => '4523678',
                'name' => 'Juan Carlos',
                'father_last_name' => 'Pérez',
                'mother_last_name' => 'Gómez',
                'phone' => '+591 71234567',
                'email' => 'juan.perez@ejemplo.com',
                'address' => 'Av. Arce #1234, Zona Central',
                'sib_departmental' => Engineer::SIB_LA_PAZ,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería Eléctrica',
                'university' => 'Universidad Mayor de San Andrés',
                'specialties' => ['Alta Tensión', 'Instalaciones Eléctricas Domiciliarias'],
            ],
            [
                'rni' => '100002',
                'ci' => '5678901',
                'name' => 'María Fernanda',
                'father_last_name' => 'López',
                'mother_last_name' => 'Vargas',
                'phone' => '+591 72345678',
                'email' => 'maria.lopez@ejemplo.com',
                'address' => 'Calle Junín #567, Zona Sopocachi',
                'sib_departmental' => Engineer::SIB_LA_PAZ,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería Civil',
                'university' => 'Universidad Mayor de San Andrés',
                'specialties' => ['Diseño Estructural', 'Hormigón Armado'],
            ],
            [
                'rni' => '100003',
                'ci' => '6789012',
                'name' => 'Carlos Alberto',
                'father_last_name' => 'Mendoza',
                'mother_last_name' => 'Rojas',
                'phone' => '+591 73456789',
                'email' => 'carlos.mendoza@ejemplo.com',
                'address' => 'Av. América #890',
                'sib_departmental' => Engineer::SIB_COCHABAMBA,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería Mecánica',
                'university' => 'Universidad Mayor de San Simón',
                'specialties' => ['Mantenimiento Industrial', 'Refrigeración y Aire Acondicionado'],
            ],
            [
                'rni' => '100004',
                'ci' => '7890123',
                'name' => 'Ana Belén',
                'father_last_name' => 'Gutiérrez',
                'mother_last_name' => 'Torres',
                'phone' => '+591 74567890',
                'email' => 'ana.gutierrez@ejemplo.com',
                'address' => 'Calle Sucre #234',
                'sib_departmental' => Engineer::SIB_SANTA_CRUZ,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería de Sistemas',
                'university' => 'Universidad Autónoma Gabriel René Moreno',
                'specialties' => ['Redes de Datos', 'Automatización y Control'],
            ],
            [
                'rni' => '100005',
                'ci' => '8901234',
                'name' => 'Roberto',
                'father_last_name' => 'Salazar',
                'mother_last_name' => 'Núñez',
                'phone' => '+591 75678901',
                'email' => 'roberto.salazar@ejemplo.com',
                'address' => 'Av. Ejército #345',
                'sib_departmental' => Engineer::SIB_TARIJA,
                'status' => Engineer::STATUS_SUSPENSION_DEFINIDA,
                'suspension_start_date' => '2024-01-15',
                'suspension_end_date' => '2025-01-15',
                'branch' => 'Ingeniería Civil',
                'university' => 'Universidad Autónoma Juan Misael Saracho',
                'specialties' => ['Vías y Carreteras', 'Topografía'],
            ],
            [
                'rni' => '100006',
                'ci' => '9012345',
                'name' => 'Patricia',
                'father_last_name' => 'Flores',
                'mother_last_name' => 'Chávez',
                'phone' => '+591 76789012',
                'email' => 'patricia.flores@ejemplo.com',
                'address' => 'Calle Bolívar #678',
                'sib_departmental' => Engineer::SIB_ORURO,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería Química',
                'university' => 'Universidad Técnica de Oruro',
                'specialties' => ['Tratamiento de Aguas Residuales', 'Gestión Ambiental'],
            ],
            [
                'rni' => '100007',
                'ci' => '0123456',
                'name' => 'Luis Fernando',
                'father_last_name' => 'Ramos',
                'mother_last_name' => 'Silva',
                'phone' => '+591 77890123',
                'email' => 'luis.ramos@ejemplo.com',
                'address' => 'Av. Busch #901',
                'sib_departmental' => Engineer::SIB_SANTA_CRUZ,
                'status' => Engineer::STATUS_SUSPENSION_INDEFINIDA,
                'suspension_start_date' => '2024-06-01',
                'suspension_end_date' => null,
                'branch' => 'Ingeniería Eléctrica',
                'university' => 'Universidad Autónoma Gabriel René Moreno',
                'specialties' => ['Media Tensión', 'Subestaciones Eléctricas'],
            ],
            [
                'rni' => '100008',
                'ci' => '1234567',
                'name' => 'Gabriela',
                'father_last_name' => 'Herrera',
                'mother_last_name' => 'Aguilar',
                'phone' => '+591 78901234',
                'email' => 'gabriela.herrera@ejemplo.com',
                'address' => 'Calle La Paz #432',
                'sib_departmental' => Engineer::SIB_CHUQUISACA,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería de Telecomunicaciones',
                'university' => 'Universidad Mayor Real y Pontificia de San Francisco Xavier de Chuquisaca',
                'specialties' => ['Telecomunicaciones', 'Redes de Datos'],
            ],
            [
                'rni' => '100009',
                'ci' => '2345678',
                'name' => 'Jorge Andrés',
                'father_last_name' => 'Mamani',
                'mother_last_name' => 'Quispe',
                'phone' => '+591 79012345',
                'email' => 'jorge.mamani@ejemplo.com',
                'address' => 'Av. 6 de Agosto #567',
                'sib_departmental' => Engineer::SIB_LA_PAZ,
                'status' => Engineer::STATUS_EMERITO,
                'branch' => 'Ingeniería Civil',
                'university' => 'Universidad Mayor de San Andrés',
                'specialties' => ['Diseño Estructural', 'Puentes'],
            ],
            [
                'rni' => '100010',
                'ci' => '3456789',
                'name' => 'Silvia',
                'father_last_name' => 'Cárdenas',
                'mother_last_name' => 'Peña',
                'phone' => '+591 70123456',
                'email' => 'silvia.cardenas@ejemplo.com',
                'address' => 'Calle Comercio #890',
                'sib_departmental' => Engineer::SIB_COCHABAMBA,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería de Sistemas',
                'university' => 'Universidad Católica Boliviana San Pablo',
                'specialties' => ['Automatización y Control', 'Gestión de Proyectos'],
            ],
            [
                'rni' => '100011',
                'ci' => '4567890',
                'name' => 'Diego Armando',
                'father_last_name' => 'Villarroel',
                'mother_last_name' => 'Suárez',
                'phone' => '+591 71234568',
                'email' => 'diego.villarroel@ejemplo.com',
                'address' => 'Av. Villazón #123',
                'sib_departmental' => Engineer::SIB_POTOSI,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería de Minas',
                'university' => 'Universidad Autónoma Tomás Frías',
                'specialties' => ['Geotecnia', 'Seguridad Industrial'],
            ],
            [
                'rni' => '100012',
                'ci' => '5678902',
                'name' => 'Daniela',
                'father_last_name' => 'Ortiz',
                'mother_last_name' => 'Miranda',
                'phone' => '+591 72345679',
                'email' => 'daniela.ortiz@ejemplo.com',
                'address' => 'Calle Aroma #456',
                'sib_departmental' => Engineer::SIB_ORURO,
                'status' => Engineer::STATUS_INACTIVO,
                'branch' => 'Ingeniería Industrial',
                'university' => 'Universidad Técnica de Oruro',
                'specialties' => ['Gestión de Proyectos', 'Supervisión de Obras'],
            ],
            [
                'rni' => '100013',
                'ci' => '6789013',
                'name' => 'Marcelo',
                'father_last_name' => 'Ríos',
                'mother_last_name' => 'Camacho',
                'phone' => '+591 73456790',
                'email' => 'marcelo.rios@ejemplo.com',
                'address' => 'Av. Circunvalación #789',
                'sib_departmental' => Engineer::SIB_SANTA_CRUZ,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería Petrolera',
                'university' => 'Universidad Autónoma Gabriel René Moreno',
                'specialties' => ['Gestión Ambiental', 'Seguridad Industrial'],
            ],
            [
                'rni' => '100014',
                'ci' => '7890124',
                'name' => 'Verónica',
                'father_last_name' => 'Reyes',
                'mother_last_name' => 'Guzmán',
                'phone' => '+591 74567891',
                'email' => 'veronica.reyes@ejemplo.com',
                'address' => 'Calle Murillo #234',
                'sib_departmental' => Engineer::SIB_BENI,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería Agronómica',
                'university' => 'Universidad Autónoma del Beni José Ballivián',
                'specialties' => ['Gestión Ambiental'],
            ],
            [
                'rni' => '100015',
                'ci' => '8901235',
                'name' => 'Fernando',
                'father_last_name' => 'Arias',
                'mother_last_name' => 'Medina',
                'phone' => '+591 75678902',
                'email' => 'fernando.arias@ejemplo.com',
                'address' => 'Av. Internacional #567',
                'sib_departmental' => Engineer::SIB_PANDO,
                'status' => Engineer::STATUS_ACTIVO,
                'branch' => 'Ingeniería Ambiental',
                'university' => 'Universidad Amazónica de Pando',
                'specialties' => ['Tratamiento de Aguas Residuales', 'Gestión Ambiental'],
            ],
        ];

        foreach ($engineers as $data) {
            $branch = Branch::where('name', $data['branch'])->first();
            $university = University::where('name', $data['university'])->first();

            if (!$branch || !$university) {
                $this->command->warn("Saltando ingeniero {$data['rni']}: rama o universidad no encontrada.");
                continue;
            }

            $engineer = Engineer::updateOrCreate(
                ['rni' => $data['rni']],
                [
                    'branch_id' => $branch->id,
                    'university_id' => $university->id,
                    'ci' => $data['ci'],
                    'name' => $data['name'],
                    'father_last_name' => $data['father_last_name'],
                    'mother_last_name' => $data['mother_last_name'] ?? null,
                    'phone' => $data['phone'] ?? null,
                    'email' => $data['email'] ?? null,
                    'address' => $data['address'] ?? null,
                    'sib_departmental' => $data['sib_departmental'],
                    'suspension_start_date' => $data['suspension_start_date'] ?? null,
                    'suspension_end_date' => $data['suspension_end_date'] ?? null,
                    'status' => $data['status'],
                ]
            );

            $specialtyIds = Specialty::whereIn('name', $data['specialties'] ?? [])->pluck('id')->toArray();
            $engineer->specialties()->sync($specialtyIds);
        }

        $this->command->info('Ingenieros creados: ' . Engineer::count());
    }
}